lr= 0.0001
lr_backbone= 1e-05
batch_size= 2
weight_decay= 0.0001
epochs= 20
lr_drop= 10
clip_max_norm= 0.1
frozen_weights= None
backbone= 'resnet50'
dilation= False
position_embedding= 'sine'
enc_layers= 6
dec_layers= 6
dim_feedforward= 2048
hidden_dim= 256
dropout= 0.1
nheads= 8
num_queries= 100
pre_norm= False
masks= False
aux_loss= True
set_cost_class= 1
set_cost_bbox= 5
set_cost_giou= 2
mask_loss_coef= 1
dice_loss_coef= 1
bbox_loss_coef= 5
giou_loss_coef= 2
eos_coef= 0.1
dataset_file= 'ytvos'
coco_path= '/data/coco'
coco_panoptic_path= None
remove_difficult= False
output_dir= '/checkpoints/haianh/detr/ytvos/'
device= 'cuda'
seed= 42
resume= 'https=//dl.fbaipublicfiles.com/detr/detr-r50-e632da11.pth'
start_epoch= 0
eval= False
num_workers= 2
world_size= 1
# dist_url= 'env=/
num_classes = 41
is_mm_model = True
tb_logdir = '/checkpoints/haianh/detr/ytvos/tensorboard'